const DEFAULTS = {
  version: 1,
  themeName: 'DEMAT-BT UI Config V1',
  colors: {
    primary: '#2563eb', primaryDark: '#1e40af', primaryLight: '#3b82f6',
    accentBlue: '#0ea5e9', accentGreen: '#10b981', accentOrange: '#f59e0b', accentRed: '#ef4444',
    text: '#0f172a', line: '#e2e8f0', card: '#ffffff', bodyBackground: '#f5f7fa'
  },
  radius: { lg: '16px' },
  shadows: {
    sm: '0 1px 3px rgba(15,23,42,0.06), 0 1px 2px rgba(15,23,42,0.04)',
    md: '0 4px 12px rgba(15,23,42,0.08), 0 2px 4px rgba(15,23,42,0.04)',
    lg: '0 20px 40px rgba(15,23,42,0.12), 0 4px 8px rgba(15,23,42,0.06)'
  },
  spacing: {
    layoutGap: '16px', layoutPadding: '16px', cardPadding: '16px',
    buttonPaddingY: '11px', buttonPaddingX: '16px'
  },
  typography: { baseFontSize: '14px', h2Size: '24px' },
  density: { mode: 'normal', tableCompact: false },
  referent: {
    gridLargeMinWidth: '480px', gridSmallMinWidth: '280px',
    groupLargeCardMinWidth: '320px', groupSmallCardMinWidth: '220px'
  },
  buttons: { fontSize: '13px', radius: '12px' }
};

const ids = [
  'primary','primaryDark','primaryLight','accentBlue','accentGreen','accentOrange','accentRed','text','line','card','bodyBackground',
  'radiusLg','buttonRadius','shadowSm','shadowMd','shadowLg',
  'layoutGap','layoutPadding','cardPadding','buttonPaddingY','buttonPaddingX','buttonFontSize','baseFontSize','h2Size',
  'densityMode','tableCompact','gridLargeMinWidth','gridSmallMinWidth','groupLargeCardMinWidth','groupSmallCardMinWidth'
];

function $(id){ return document.getElementById(id); }

function setDefaults(){
  $('primary').value = DEFAULTS.colors.primary;
  $('primaryDark').value = DEFAULTS.colors.primaryDark;
  $('primaryLight').value = DEFAULTS.colors.primaryLight;
  $('accentBlue').value = DEFAULTS.colors.accentBlue;
  $('accentGreen').value = DEFAULTS.colors.accentGreen;
  $('accentOrange').value = DEFAULTS.colors.accentOrange;
  $('accentRed').value = DEFAULTS.colors.accentRed;
  $('text').value = DEFAULTS.colors.text;
  $('line').value = DEFAULTS.colors.line;
  $('card').value = DEFAULTS.colors.card;
  $('bodyBackground').value = DEFAULTS.colors.bodyBackground;

  $('radiusLg').value = DEFAULTS.radius.lg;
  $('buttonRadius').value = DEFAULTS.buttons.radius;
  $('shadowSm').value = DEFAULTS.shadows.sm;
  $('shadowMd').value = DEFAULTS.shadows.md;
  $('shadowLg').value = DEFAULTS.shadows.lg;

  $('layoutGap').value = DEFAULTS.spacing.layoutGap;
  $('layoutPadding').value = DEFAULTS.spacing.layoutPadding;
  $('cardPadding').value = DEFAULTS.spacing.cardPadding;
  $('buttonPaddingY').value = DEFAULTS.spacing.buttonPaddingY;
  $('buttonPaddingX').value = DEFAULTS.spacing.buttonPaddingX;
  $('buttonFontSize').value = DEFAULTS.buttons.fontSize;
  $('baseFontSize').value = DEFAULTS.typography.baseFontSize;
  $('h2Size').value = DEFAULTS.typography.h2Size;

  $('densityMode').value = DEFAULTS.density.mode;
  $('tableCompact').value = String(DEFAULTS.density.tableCompact);

  $('gridLargeMinWidth').value = DEFAULTS.referent.gridLargeMinWidth;
  $('gridSmallMinWidth').value = DEFAULTS.referent.gridSmallMinWidth;
  $('groupLargeCardMinWidth').value = DEFAULTS.referent.groupLargeCardMinWidth;
  $('groupSmallCardMinWidth').value = DEFAULTS.referent.groupSmallCardMinWidth;
}

function readModel(){
  return {
    version: 1,
    enabled: true,
    themeName: 'DEMAT-BT UI Config V1',
    colors: {
      primary: $('primary').value,
      primaryDark: $('primaryDark').value,
      primaryLight: $('primaryLight').value,
      accentBlue: $('accentBlue').value,
      accentGreen: $('accentGreen').value,
      accentOrange: $('accentOrange').value,
      accentRed: $('accentRed').value,
      text: $('text').value,
      line: $('line').value,
      card: $('card').value,
      bodyBackground: $('bodyBackground').value
    },
    radius: { lg: $('radiusLg').value },
    shadows: { sm: $('shadowSm').value, md: $('shadowMd').value, lg: $('shadowLg').value },
    spacing: {
      layoutGap: $('layoutGap').value,
      layoutPadding: $('layoutPadding').value,
      cardPadding: $('cardPadding').value,
      buttonPaddingY: $('buttonPaddingY').value,
      buttonPaddingX: $('buttonPaddingX').value
    },
    typography: { baseFontSize: $('baseFontSize').value, h2Size: $('h2Size').value },
    density: { mode: $('densityMode').value, tableCompact: $('tableCompact').value === 'true' },
    referent: {
      gridLargeMinWidth: $('gridLargeMinWidth').value,
      gridSmallMinWidth: $('gridSmallMinWidth').value,
      groupLargeCardMinWidth: $('groupLargeCardMinWidth').value,
      groupSmallCardMinWidth: $('groupSmallCardMinWidth').value
    },
    buttons: { fontSize: $('buttonFontSize').value, radius: $('buttonRadius').value }
  };
}

function generateCss(cfg){
  return `/* Generated by Config UI DEMAT-BT (autonomous app) */
:root {
  --primary:${cfg.colors.primary};
  --primary-dark:${cfg.colors.primaryDark};
  --primary-light:${cfg.colors.primaryLight};
  --accent-blue:${cfg.colors.accentBlue};
  --accent-green:${cfg.colors.accentGreen};
  --accent-orange:${cfg.colors.accentOrange};
  --accent-red:${cfg.colors.accentRed};
  --txt:${cfg.colors.text};
  --line:${cfg.colors.line};
  --card:${cfg.colors.card};
  --bg:${cfg.colors.bodyBackground};
  --radius:${cfg.radius.lg};
  --shadow-sm:${cfg.shadows.sm};
  --shadow:${cfg.shadows.md};
  --shadow-lg:${cfg.shadows.lg};
  --ui-layout-gap:${cfg.spacing.layoutGap};
  --ui-layout-padding:${cfg.spacing.layoutPadding};
  --ui-card-padding:${cfg.spacing.cardPadding};
  --ui-btn-py:${cfg.spacing.buttonPaddingY};
  --ui-btn-px:${cfg.spacing.buttonPaddingX};
  --ui-btn-font-size:${cfg.buttons.fontSize};
  --ui-btn-radius:${cfg.buttons.radius};
  --ui-font-size-base:${cfg.typography.baseFontSize};
  --h2-size:${cfg.typography.h2Size};
  --ui-grid-large-min:${cfg.referent.gridLargeMinWidth};
  --ui-grid-small-min:${cfg.referent.gridSmallMinWidth};
  --ui-group-large-min:${cfg.referent.groupLargeCardMinWidth};
  --ui-group-small-min:${cfg.referent.groupSmallCardMinWidth};
}
.layout{gap:var(--ui-layout-gap);padding:var(--ui-layout-padding)}
.card,.briefCard,.btCard,.modal__panel,.brief-table-container,.stat-box,.param-card{border-radius:var(--radius);box-shadow:var(--shadow)}
.card__title,.btCard,.briefCard{padding:var(--ui-card-padding)}
.btn,.doc-btn{padding:var(--ui-btn-py) var(--ui-btn-px);font-size:var(--ui-btn-font-size);border-radius:var(--ui-btn-radius)}
.grid{grid-template-columns:repeat(auto-fill,minmax(var(--ui-grid-large-min),1fr))}
.grid--small{grid-template-columns:repeat(auto-fill,minmax(var(--ui-grid-small-min),1fr))}
.referent-group--large .referent-group__grid{grid-template-columns:repeat(auto-fill,minmax(var(--ui-group-large-min),1fr))}
.referent-group--small .referent-group__grid{grid-template-columns:repeat(auto-fill,minmax(var(--ui-group-small-min),1fr))}
body{font-size:var(--ui-font-size-base)}
.h2{font-size:var(--h2-size)}
${cfg.density.mode === 'compact' ? 'body{--ui-btn-py:8px;--ui-btn-px:12px;--ui-card-padding:12px;}' : ''}
${cfg.density.mode === 'comfortable' ? 'body{--ui-btn-py:13px;--ui-btn-px:18px;--ui-card-padding:18px;}' : ''}
${cfg.density.tableCompact ? 'table.brief-table td,table.history-table td,.bt-list__table td{padding-top:4px!important;padding-bottom:4px!important;}' : ''}
`;
}

function applyPreview(cfg){
  const root = document.documentElement.style;
  root.setProperty('--primary', cfg.colors.primary);
  root.setProperty('--primary-dark', cfg.colors.primaryDark);
  root.setProperty('--line', cfg.colors.line);
  root.setProperty('--card', cfg.colors.card);
  root.setProperty('--radius', cfg.buttons.radius);
  root.setProperty('--shadow', cfg.shadows.md);
  root.setProperty('--bg', cfg.colors.bodyBackground);
}

function download(filename, content, type){
  const blob = new Blob([content], { type });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = filename;
  a.click();
  URL.revokeObjectURL(a.href);
}

function render(){
  const cfg = readModel();
  const css = generateCss(cfg);
  $('jsonOutput').value = JSON.stringify(cfg, null, 2);
  $('cssOutput').value = css;
  applyPreview(cfg);
}

function exportNotes(){
  const notes = `# Integration notes (manual)
1. Copier le JSON vers: config/ui-demat-bt.json
2. Copier le CSS vers: css/config-ui-demat-bt.override.css
3. Option d'intégration minimale dans DEMAT-BT (manuelle):
   - ajouter le link CSS après styles.css/components.css
   - ou conserver en artefact de recette sans intégration directe
4. Ne pas toucher la logique métier JS (pdf-extractor, classify, cache, export, state).
`;
  download('integration-notes.generated.md', notes, 'text/markdown;charset=utf-8');
}

window.addEventListener('DOMContentLoaded', () => {
  setDefaults();
  ids.forEach(id => $(id).addEventListener('input', render));
  ids.forEach(id => $(id).addEventListener('change', render));
  $('btnReset').addEventListener('click', () => { setDefaults(); render(); });
  $('btnExportJson').addEventListener('click', () => download('ui-demat-bt.generated.json', $('jsonOutput').value, 'application/json;charset=utf-8'));
  $('btnExportCss').addEventListener('click', () => download('config-ui-demat-bt.override.generated.css', $('cssOutput').value, 'text/css;charset=utf-8'));
  $('btnExportNotes').addEventListener('click', exportNotes);
  render();
});
